config/routes.rb
Bluestone::Application.routes.draw do
  resources :scores

  get 'users/login', to: 'user_login#login'

  resources :users

  resources :developers
  
  resources :apps do
	resources :leaderboards do
		resources :scores
	end
  end
 
  root 'apps#index'
  
  get 'developer_login', to: 'developer_login#login'
  post 'developer_login', to: 'developer_login#login'

  get 'developer_login/login_form', to: 'developer_login#login_form'
  get 'developer_login/logout', to: 'developer_login#logout'
  

  

end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
	belongs_to :app
	has_many :scores, :dependent => :destroy


	def api_fields(base_uri)
		{
			:id => id,
			:app_id => app_id,
			:name => name,
			:create_at => created_at,
			:updated_at => updated_at
		}
	end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :set_app
  before_action :set_leaderboard, only: [:show, :edit, :update, :destroy]

  # GET /leaderboards
  # GET /leaderboards.json
  def index
    @leaderboards = @app.leaderboards.all
  end

  # GET /leaderboards/1
  # GET /leaderboards/1.json
  def show
	@leaderboards = @app.leaderboards.all
	@scores = @leaderboard.scores.find(:all, :order => "value DESC")
  end

  # GET /leaderboards/new
  def new
	#@leaderboard = Leaderboard.new
    #@leaderboard.app = @app
     @leaderboard = @app.leaderboards.new
	
	 respond_to do |format|
		format.html # new.html.erb
		format.json { render json: @leaderboard.api_fields(request_base_uri) }
	 end
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards
  # POST /leaderboards.json
  def create
    @leaderboard = @app.leaderboards.new(leaderboard_params)
    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to [@app, @leaderboard], notice: 'Leaderboard was successfully created.' }
        format.json { render action: 'show', status: :created, location: @leaderboard }
      else
        format.html { render action: 'new' }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1
  # PATCH/PUT /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to [@app,@leaderboard], notice: 'Leaderboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1
  # DELETE /leaderboards/1.json
  def destroy
    @leaderboard.destroy
    respond_to do |format|
      format.html { redirect_to app_leaderboard_path(@app, nil) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaderboard
      @leaderboard = @app.leaderboards.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leaderboard_params
      params.require(:leaderboard).permit(:icon, :name)
    end
	
	def set_app
		@app = App.find(params[:app_id])
	end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/leaderboards/_form.html.erb
<%= form_for([@app, @leaderboard]) do |f| %>
  <% if @leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% @leaderboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :app_id %>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaderboards/edit.html.erb
<h1>Editing leaderboard</h1>

<%= render 'form' %>

<%= link_to 'Show', app_leaderboard_path(@app, @leaderboard) %> |
<%= link_to 'Back', app_leaderboards_path(@app) %>

app/views/leaderboards/index.html.erb
<h1>Listing leaderboards</h1>

<table>
  <thead>
    <tr>
      <th>Icon</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderboards.each do |leaderboard| %>
      <tr>
        <td><%= leaderboard.icon %></td>
        <td><%= leaderboard.name %></td>
        <td><%= #link_to 'Show', leaderboard
			link_to 'Show', app_leaderboard_path(@app, leaderboard)
 %></td>

        <td><%= link_to 'Edit', edit_app_leaderboard_path(@app, leaderboard)  %></td>
        <td><%= link_to 'Destroy', [@app, leaderboard], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leaderboard', new_app_leaderboard_path %>

app/views/leaderboards/new.html.erb
<h1>New leaderboard</h1>

<%= render 'form' %>

<%= link_to 'Back', app_leaderboards_path(@app) %>

app/views/leaderboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Icon:</strong>
  <%= @leaderboard.icon %>
</p>

<p>
  <strong>Name:</strong>
  <%= @leaderboard.name %>
</p>

<p>
  <strong>Scores List</strong>
</p>
<table>
	<tr>
		<td align="cneter">User Name</td>
		<td align="center">Score</td>
		<td align="center">Score Display</td>
	</tr>
  <% @scores.each do |score| %>
	<tr>
		<td align="center"><%= score.user.name %></td>
		<td align="center"><%= score.value %></td>
		<td align="center"><%= score.display_string %></td>
	</tr>
  <% end %>
</table>
<p align="center">
<%= link_to 'Add Score', new_app_leaderboard_score_path(@app, @leaderboard, @score) %>
</p>

<%= link_to 'Edit', edit_app_leaderboard_path(@app,@leaderboard) %> |
<%= link_to 'Back', app_leaderboards_path(@app) %>