config/routes.rb
Bluestone::Application.routes.draw do
  resources :scores

  get 'users/login', to: 'user_login#login'

  resources :users

  resources :developers
  
  resources :apps do
	resources :leaderboards do
		resources :scores
	end
  end
 
  root 'apps#index'
  
  get 'developer_login', to: 'developer_login#login'
  post 'developer_login', to: 'developer_login#login'

  get 'developer_login/login_form', to: 'developer_login#login_form'
  get 'developer_login/logout', to: 'developer_login#logout'
  

  

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user
	belongs_to :leaderboard
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  protect_from_forgery :except => :create
  before_action :set_score, only: [:show, :edit, :update, :destroy]
  before_action :set_app
  before_action :set_leaderboard

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = @leaderboard.scores.new

  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to [@app, @leaderboard, @score], notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:leaderboard_id, :user_id, :value, :display_string)
    end
	
	def set_app
		@app = App.find(params[:app_id])
	end	
	
	def set_leaderboard
		@leaderboard = Leaderboard.find(params[:leaderboard_id])
	end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for([@app, @leaderboard, @score]) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :leaderboard_id %><br>
    <%= f.number_field :leaderboard_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :display_string %><br>
    <%= f.text_field :display_string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <thead>
    <tr>
      <th>Leaderboard</th>
      <th>User</th>
      <th>Value</th>
      <th>Display string</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.leaderboard_id %></td>
        <td><%= score.user_id %></td>
        <td><%= score.value %></td>
        <td><%= score.display_string %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_app_leaderboard_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', app_leaderboard_path(@app, @leaderboard) %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Leaderboard:</strong>
  <%= @score.leaderboard_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @score.user_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @score.value %>
</p>

<p>
  <strong>Display string:</strong>
  <%= @score.display_string %>
</p>

<%= link_to 'Edit', edit_app_leaderboard_score_path(@app, @leaderboard, @score) %> |
<%= link_to 'Back', app_leaderboard_path(@app, @leaderboard) %>