config/routes.rb
Bluestone::Application.routes.draw do
  resources :scores

  get 'users/login', to: 'user_login#login'

  resources :users

  resources :developers
  
  resources :apps do
	resources :leaderboards do
		resources :scores
	end
  end
 
  root 'apps#index'
  
  get 'developer_login', to: 'developer_login#login'
  post 'developer_login', to: 'developer_login#login'

  get 'developer_login/login_form', to: 'developer_login#login_form'
  get 'developer_login/logout', to: 'developer_login#logout'
  

  

end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :app_key %><br>
    <%= f.text_field :app_key %>
  </div>
	<%= f.hidden_field :developer_id %> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<div class="page-header">
  <h1>Apps <small>Apps Management</small></h1>
</div>
<p align="right">
	<%= link_to 'Log out', {:controller => :developer_login, action: 'logout'}, :class => 'btn btn-primary' %>
</p>
<p align="right">
	<%= link_to 'Accounts', developers_path, :class => 'btn btn-primary' %>
</p>
<p align="right">
	<%= link_to 'Account_setting', developer_path(session[:developer_id]), :class => 'btn btn-primary' %>
</p>
<div class="panel panel-default">
    <div class="panel-heading">Panel heading</div>
    <div class="panel-body">App is...</div>
    <table class="table">
      <thead>
        <tr>
          <th>Icon</th>
          <th>Name</th>
          <th>App key</th>
          <th>Control</th>
        </tr>
      </thead>

      <tbody>
        <% @apps.each do |app| %>
        <tr>
          <td><%= app.icon %></td>
          <td><%= app.name %></td>
          <td><%= app.app_key %></td>
          <td><%= link_to 'Show', app, :class => 'btn btn-success' %>
              <%= link_to 'Edit', edit_app_path(app), :class => 'btn btn-info' %>
              <%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
        </tr>
        <% end %>
      </tbody>
  </table>
</div>
<br>

<%= link_to 'New App', new_app_path, :class => 'btn btn-primary' %>
<% #debug request.protocol %>
<% #debug request.host_with_port %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Icon:</strong>
  <%= @app.icon %>
</p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>App key:</strong>
  <%= @app.app_key %>
</p>

<p>
  <strong>Leaderboard:</strong>
  <%= link_to 'Leaderboard List', app_leaderboards_path(@app, nil) %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>